### ISSUE TITLE
Update on discrepancy between potency results of OSM-S-412

### ISSUE THREAD

**Issue by david1597** [OpenSourceMalaria/Series4#20]
The results obtained from Dundee in early January indicated that compound OSM-S-412, the original "Pfizer phenol" did not have the same potency (#10). The compound sent from our lab had a potency of around 4.5 uM while that from the original biosynthesis was < 9 nM (OpenSourceMalaria/OSM_To_Do_List/issues/513). 

We need to figure out why. There is currently no reason to question the assay itself, so we're working on the assumption that they were not the actually the same sample at the time of testing. Potential reasons why are detailed below, but to confirm once and for all a second synthesis of the latter stages is currently underway and will be ready for sending to Dundee in a couple of weeks - along with a shipment of related compounds (OpenSourceMalaria/OSM_To_Do_List/issues/554) made by myself and Josh (OpenSourceMalaria/OSM_To_Do_List/issues/554). 

A brief discussion then on the samples...Scott Obach sent through the NMR from his biosynthesised compound (top) and it's shown here with my sample (bottom). Direct comparison isn't possible as they were run in different solvents, but the same number and type of peaks match - and they're what we would expect. All good so far. However, my sample there was run on the 200 MHz instrument to confirm that the benzyl deprotection had worked. I then tried to run a further proton and a carbon on the 400 MHz, but, the sample crashed out of solution overnight whilst this was happening. Hmmmm. Potentially we had a reaction occuring during this time and OSM-S-412 converted to something else. It was shipped regardless as we tried to meet that deadline.
![presentation1](https://user-images.githubusercontent.com/30584472/35126183-7b425d76-fd00-11e7-9f01-fc11a9dc30f5.jpg)

Another possibility, although I don't believe it can explain the entire result observed here relates to potential chirality as mentioned by @drc007 [here](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/513#issuecomment-318265606). The biosynthesis compound may have been chiral. I would have made a racemic mixture. Is it possible that the precipitation observed even enriched one enantiomer - the more inactive one, if indeed that is what we have. This is not something I've encountered before so my knowledge is limited a bit here. Regardless, this topic is something we should probably keep in mind and be aware of.

Lastly, it's also possible there was a, umm, human error and the wrong vial was simply labelled and shipped. I would be disappointed to admit that this entire problem is a result of me mislabelling a vial, but maybe it would also be the best option and that the chemistry and biology is as we hope! 

The re-resynthesis is on a larger scale now we understand and are handling the chemistry well. There will be enough compound for stability testing etc in addition for various biological tests. We will provide further updates over the next few weeks.

**Comment by drc007** [comment]
Given your comment on solubility under NMR conditions, is it possible the sample precipitated during the bioassay?

**Comment by cdsouthan** [comment]
This shows good engagement for getting to the bottom of this.  I think those from other med chem operations, even or especially in big pharma, would testify to this not being such a rare occurrence but often gets swept under the carpet.   So another advantage of our openness is to explore just such cases.  The investigation steps seem the right way to go ( including checking good ole' mislabeling a bottle, but no blame!),  so I'll just add a few 101s

a) try not to run out of any individual original or re-made batches so you can always go back and re-run both the assay and the chemistry analytics on both batches exactly in //
b) logically we should get an assay re-test of the original SO batch and also to do his own biosyn  re-make
c) what is the re-syn plus re-assy consistency of other compounds in this series? 
d) this occurrence raises the issue of intra-assay internal standards brought up by @MedChemProf i.e. the need to get a large-ish batches of  selected  100 nM and a 1.0 uM actives for small aliquots to be handled in // and shipped with every assay batch (where they should also have their own internal control of a standard artemisinin)
e) d) is also relevant for checking inter-assay variation between the different assay centers

**Comment by MFernflower** [comment]
Could the compound's alkyl alcohol moiety oxidized in air into a carboxylic acid?  @david1597

**Comment by mcoster** [comment]
@MFernflower - never say never, but that's not at all common. Aldehydes can autoxidise, often slowly, but unactivated primary alcohols are normally extremely stable towards oxygen.

**Comment by MFernflower** [comment]
I figured it would not oxidize as it looked like a rather stable drug but still - what caused these odd results?

**Comment by cdsouthan** [comment]
Analytical HPLC been done?

**Comment by MFernflower** [comment]
^^^^ I second that idea!

@mattodd do you have access to a HPLC machine or will the samples need to be shipped off? 

Hopefully we will be able to move away from this rather troublesome phenolic architecture once Josh's compounds are screened against the parasite but only time will tell it seems!

**Comment by david1597** [comment]
@cdsouthan @MFernflower I didn’t run any HPLC on the compound, although we do have the facilities to be able to do this. Scott Obach has also offered to run it on their HPLC-UV-HRMS for a comparison.

**Comment by david1597** [comment]
@drc007 Potentially. My NMR sample was in acetone and precipitated from that. The assay uses DMSO and then dilutes. So different solvents but again something to be aware of. I’ll investigate solubility and stability in the each solvent more thoroughly when more compound is made (which should be by end of Jan).

**Comment by MFernflower** [comment]
@david1597 Have you attempted to rotovap the stuff in the NMR tube yet?

**Comment by cdsouthan** [comment]
@david1597 try to get the logical controls done first, or you risk going round in circles

**Comment by mattodd** [comment]
The precipitation of this compound from acetone is surprising to me, and appeared to happen over time. That does suggest something chemical might be occurring, though I'd agree with @mcoster that there's no particular reason to expect this in this case. If Scott's sample did not have such issues, then perhaps there is something in the way in which this sample was stored in shipping that prevented such a change.  I think Scott's sample arose from a final oxidation step, while David's did not. But this is all speculation that the resynthesis and re-screen could sort out. Still the most likely explanation is that something happened to the chemical synthesis sample between synthesis and evaluation.

Yes, HPLC is fine and easy, but we typically don't resort to it when we have a good 1H spectrum for a sample that displays no unusual solubility behaviour. 

I'd agree that a re-test of the Obach sample already in Dundee would be a good idea, if it is still there (@david1597 could you please check?). Scott has (by email) said "If you have 1 mg [of the phenol] to spare, you could send us some of what you made and we can compare it on our HPLC-UV-HRMS and NMR systems." which seems sensible once David's resynthesis is done. I've asked Scott if a repeat of the biosynthesis is feasible and whether they need more starting material, should we get to that point (which is not yet).

@david1597  mentioned an idea about the biosynthesized sample being potentially enantioenriched. It's possible (but not something I see as likely in this setting) for the racemate to crystallize/precipitate/aggregate, artificially enriching the ee in solution in what is known in catalysis fields as a positive nonlinear effect. Low on my list of possibilities, though would be interesting.

As @cdsouthan says this is a real-world problem and it's very good that we're engaging with this in an open way. It does highlight the need for us always to post all the raw data associated with experiments, and in this case I ought to have asked Scott to share with us the raw spectroscopic data, rather than assuming the data were fine, so that we could check in advance. (@david1597  - can you post the full spec data we received from Scott, please, if it's not already somewhere.) But - interestingly - I'm not sure in this case that that would have helped.

**Comment by drc007** [comment]
@mattodd @david1597 "The "Pfizer phenol" lab resynthesis - OSM-S-412 - has come back at 3.23 µM. This is in agreement with a batch sent before Christmas ( #10). It does not agree with the original biosynthesis which showed a single digit nM potency."
Good news that we have confirmed the activity of the synthesised sample, this still leaves a question over the compound isolated from biotransformation. We would only expect a 2-fold improvement activity for the single enantiomer so I don't think this is the answer.

Have we considered the structure below, which could arise from oxidation of difluromethoxy?

![biotrans](https://user-images.githubusercontent.com/7080516/37861816-66f72ee4-2f39-11e8-9417-50a0571335e4.png)

Should be possible to check using mass spec or Fluorine NMR.

**Comment by edwintse** [comment]
It's a little harder to tell from the Pfizer NMR image but it still looks like there is the characteristic triplet that you get from the OCHF2 group and it doesn't quite explain the difference in shifts in the upfield signals, but we can have a close look when we get the raw data.

**Comment by cdsouthan** [comment]
When will the results of a re-test of the 9nM come back and how much remains of that  batch?

**Comment by david1597** [comment]
@cdsouthan All that remains of the original batch is about 30 uL of unknown conc. (~0.5 mM) in Dundee -  its been sat around at room temp for half a year though as well, so may be of limited use.

**Comment by david1597** [comment]
@drc007 We now have the raw 1H data and I've set up #33 to discuss in more detail. It looks like the OC**H**F2 triplet is still present, although interestingly, it has shifted in the spectrum.

**Comment by david1597** [comment]
Closing this issue.

It served as an update on the difference in potency between the biosynthesis and subsequent lab synthesis. As is currently being discussed in #33, it now appears that this is because they were different molecules! #33 aims to identify the structure of that original nM potent compound.
