### ISSUE TITLE
Next batch of compounds sent for biological testing Feb 2018

### ISSUE THREAD

**Issue by edwintse** [OpenSourceMalaria/Series4#26]
The first batch of compounds for year (shown below) have now been shipped to Dundee for screening against _P. falciparum_.

UPDATE 24/3/18 RESULTS ARE IN AND ARE POSTED BELOW.
--------------------------------------------------------------------------------------------------
- Miscellaneous compounds (L to R): The hERG evador (#22), the 4-chlorophenol for IVIVC evaluation ([#389](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/389)), the Pfizer phenol resynthesised by @david1597 (#23), the bis ether synthesised by @maratsydney
- Suzuki compounds: Second batch of compounds made through Suzuki coupling made by @maratsydney (first batch #8)
- Norcross compounds: First set of Norcross compounds made by @maratsydney ([#537](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/537))

![dundee compounds 260218](https://user-images.githubusercontent.com/18062981/36649440-472b5aba-1af1-11e8-81c5-589a679c6d1c.png)
--------------------------------------------------------------------------------------------------
MMV Number | SMILES | InChI | InChI Key
-- | -- | -- | --
MMV1579336 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(C(O)=O)C4=CC=CC=C4)N32 | InChI=1S/C21H16F2N4O4/c22-21(23)31-15-8-6-14(7-9-15)19-26-25-17-10-24-11-18(27(17)19)30-12-16(20(28)29)13-4-2-1-3-5-13/h1-11,16,21H,12H2,(H,28,29) | FICNFVPYGUTYFV-UHFFFAOYSA-N
MMV669784 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OC4=CC=C(Cl)C=C4)N32 | InChI=1S/C18H11ClF2N4O2/c19-12-3-7-13(8-4-12)26-16-10-22-9-15-23-24-17(25(15)16)11-1-5-14(6-2-11)27-18(20)21/h1-10,18H | WXNPYOXFQUYIOI-UHFFFAOYSA-N
MMV1579337 | FC1=CC(CCOC2=CN=CC3=NN=C(N4CCOCC4)N32)=CC=C1F | InChI=1S/C17H17F2N5O2/c18-13-2-1-12(9-14(13)19)3-6-26-16-11-20-10-15-21-22-17(24(15)16)23-4-7-25-8-5-23/h1-2,9-11H,3-8H2 | BBKXHWRASNHAOR-UHFFFAOYSA-N
MMV1579338 | FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC=CC(C(N(C)C)=O)=C4)N32)=CC=C1F | InChI=1S/C22H19F2N5O2/c1-28(2)22(30)16-5-3-4-15(11-16)21-27-26-19-12-25-13-20(29(19)21)31-9-8-14-6-7-17(23)18(24)10-14/h3-7,10-13H,8-9H2,1-2H3 | PWLRVFJPMJABKE-UHFFFAOYSA-N
MMV1579339 | FC(C(F)=C1)=CC=C1CCOC2=CN=CC3=NN=C(OCCC4=CC(F)=C(F)C=C4)N32 | InChI=1S/C21H16F4N4O2/c22-15-3-1-13(9-17(15)24)5-7-30-20-12-26-11-19-27-28-21(29(19)20)31-8-6-14-2-4-16(23)18(25)10-14/h1-4,9-12H,5-8H2 | PCFGQRSVXZZXPK-UHFFFAOYSA-N
MMV1579340 | FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC=C(N5CCOCC5)C=C4)N32)=CC=C1F | InChI=1S/C23H21F2N5O2/c24-19-6-1-16(13-20(19)25)7-10-32-22-15-26-14-21-27-28-23(30(21)22)17-2-4-18(5-3-17)29-8-11-31-12-9-29/h1-6,13-15H,7-12H2 | YZCOBAJWPPWSFU-UHFFFAOYSA-N
MMV1579341 | FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC=C5C(NC=C5)=C4)N32)=CC=C1F | InChI=1S/C21H15F2N5O/c22-16-4-1-13(9-17(16)23)6-8-29-20-12-24-11-19-26-27-21(28(19)20)15-3-2-14-5-7-25-18(14)10-15/h1-5,7,9-12,25H,6,8H2 | VHFREJHLTSVZGA-UHFFFAOYSA-N
MMV1579342 | FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC=C(N)C=C4)N32)=CC=C1F | InChI=1S/C19H15F2N5O/c20-15-6-1-12(9-16(15)21)7-8-27-18-11-23-10-17-24-25-19(26(17)18)13-2-4-14(22)5-3-13/h1-6,9-11H,7-8,22H2 | PGJZGRJIPPSPJV-UHFFFAOYSA-N
MMV1579343 | FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC=C(N5CCCCC5)C=C4)N32)=CC=C1F | InChI=1S/C24H23F2N5O/c25-20-9-4-17(14-21(20)26)10-13-32-23-16-27-15-22-28-29-24(31(22)23)18-5-7-19(8-6-18)30-11-2-1-3-12-30/h4-9,14-16H,1-3,10-13H2 | IBAQRAIPMINXCX-UHFFFAOYSA-N
MMV1579344 | FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC=C(N5CCCC5)C=C4)N32)=CC=C1F | InChI=1S/C23H21F2N5O/c24-19-8-3-16(13-20(19)25)9-12-31-22-15-26-14-21-27-28-23(30(21)22)17-4-6-18(7-5-17)29-10-1-2-11-29/h3-8,13-15H,1-2,9-12H2 | MKNMPQGWOUWNLB-UHFFFAOYSA-N
MMV1579345 | FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC=C(NC(C)=O)C=C4)N32)=CC=C1F | InChI=1S/C21H17F2N5O2/c1-13(29)25-16-5-3-15(4-6-16)21-27-26-19-11-24-12-20(28(19)21)30-9-8-14-2-7-17(22)18(23)10-14/h2-7,10-12H,8-9H2,1H3,(H,25,29) | PLEIRUOVWBUIKA-UHFFFAOYSA-N
MMV1579346 | FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC=CC(NC(C)=O)=C4)N32)=CC=C1F | InChI=1S/C21H17F2N5O2/c1-13(29)25-16-4-2-3-15(10-16)21-27-26-19-11-24-12-20(28(19)21)30-8-7-14-5-6-17(22)18(23)9-14/h2-6,9-12H,7-8H2,1H3,(H,25,29) | DFKJCMXUKUTORD-UHFFFAOYSA-N
MMV1579347 | FC1=CC(CCOC2=CN=CC3=NN=C(N4CCC(F)(F)CC4)N32)=CC=C1F | InChI=1S/C18H17F4N5O/c19-13-2-1-12(9-14(13)20)3-8-28-16-11-23-10-15-24-25-17(27(15)16)26-6-4-18(21,22)5-7-26/h1-2,9-11H,3-8H2 | QEKAFCQAHVHCHN-UHFFFAOYSA-N
MMV1579348 | FC1=CC(CCOC2=CN=CC3=NN=C(N4CCC(F)CC4)N32)=CC=C1F | InChI=1S/C18H18F3N5O/c19-13-3-6-25(7-4-13)18-24-23-16-10-22-11-17(26(16)18)27-8-5-12-1-2-14(20)15(21)9-12/h1-2,9-11,13H,3-8H2 | XGYZBGPCRAEWAT-UHFFFAOYSA-N
MMV1579349 | FC1=CC(CCOC2=CN=CC3=NN=C(N4CCC(C(F)(F)F)CC4)N32)=CC=C1F | InChI=1S/C19H18F5N5O/c20-14-2-1-12(9-15(14)21)5-8-30-17-11-25-10-16-26-27-18(29(16)17)28-6-3-13(4-7-28)19(22,23)24/h1-2,9-11,13H,3-8H2 | VSNCNIYPDHLNGV-UHFFFAOYSA-N
MMV1579350 | FC1=C(F)C=C(CCOC2=CN=CC3=NN=C(N4CCN(C)CC4)N32)C=C1 | InChI=1S/C18H20F2N6O/c1-24-5-7-25(8-6-24)18-23-22-16-11-21-12-17(26(16)18)27-9-4-13-2-3-14(19)15(20)10-13/h2-3,10-12H,4-9H2,1H3 | PXDXCQZMCIITIC-UHFFFAOYSA-N
MMV1579351 | FC1=CC(CCOC2=CN=CC3=NN=C(C4=CC=C(N(C)C)C=C4)N32)=CC=C1F | InChI=1S/C21H19F2N5O/c1-27(2)16-6-4-15(5-7-16)21-26-25-19-12-24-13-20(28(19)21)29-10-9-14-3-8-17(22)18(23)11-14/h3-8,11-13H,9-10H2,1-2H3 | DWKVYGNKXDMKJI-UHFFFAOYSA-N
MMV1557865 | FC(F)OC(C=C1)=CC=C1C2=NN=C3C=NC=C(OCC(CO)C4=CC=C(O)C=C4)N32 | InChI=1S/C21H18F2N4O4/c22-21(23)31-17-7-3-14(4-8-17)20-26-25-18-9-24-10-19(27(18)20)30-12-15(11-28)13-1-5-16(29)6-2-13/h1-10,15,21,28-29H,11-12H2 | BCDILCAJSSYWKE-UHFFFAOYSA-N

[Dundee Compounds 260218.zip](https://github.com/OpenSourceMalaria/Series4/files/1756983/Dundee.Compounds.260218.zip)

**Comment by david1597** [comment]
Results are in. Data shown is the average of two runs. Data has been added to the [Master List](https://docs.google.com/spreadsheets/d/1Rvy6OiM291d1GN_cyT6eSw_C3lSuJ1jaR7AJa8hgGsc/edit#gid=510297618), and to the '[Biological Data currently not incorporated into the main Wiki sections wiki](https://github.com/OpenSourceMalaria/Series4/wiki/Biological-Data-currently-not-incorporated-into-the-main-Wiki-sections)' 

![dundee results 260218](https://user-images.githubusercontent.com/30584472/37855349-f7c372b2-2f42-11e8-9330-1162d98036f6.png)

[Dundee Results 260218.zip](https://github.com/OpenSourceMalaria/Series4/files/1843688/Dundee.Results.260218.zip)

**Comment by david1597** [comment]
* One of the Suzuki compounds - OSM-S-525 - is a stand-out with a potency of 86 nM making it one of the most potent series 4 compounds to date. It may be worth exploring around this structure further. The others in this series are generally inactive.

* the "Pfizer phenol" lab synthesis - OSM-S-412 - has come back at 3.23 µM. This is in agreement with a batch sent before Christmas ( #10). It does not agree with the [original biosynthesis](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/513) which showed a single digit nM potency. Further discussion on this at #20. 
   * Our current reasoning is that the structure proposed from that biosynthesis was incorrect; we're basing this on differences observed in the NMR spectra. Discussion on this is at #24, and we're awaiting further data to provide further insight.
   * There is a _chance_, a _small chance_, that the original hit may be due to a single enantiomer that was preferentially formed in the biosynthesis. 

* the [Norcross compounds](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/537) are generally inactive

**Comment by cdsouthan** [comment]
OSM-S-525 potency is certainly encouraging but a re-syn and a replicated re-test at two assay centres would be in order (and can go in the paper as a diligent reproducability test).  If this goes well we might even convince Tocris to put it up as a purchasable reference cpd

**Comment by MFernflower** [comment]
Fantastic work @maratsydney 
Are the indazole and n-methylindole variants in the works?

**Comment by mattodd** [comment]
Hi @david1597 @edwintse does one of you have the above data (in whatever form we get them from ScienceCloud) posted somewhere on the ELN? We ought to have the primary data there, with the summary data here and on the wiki. Also, the image on the "[Not yet added to the wiki](https://github.com/OpenSourceMalaria/Series4/wiki/Biological-Data-currently-not-incorporated-into-the-main-Wiki-sections)" page also needs some link back to an ELN. We will need links of this kind to primary data for the paper.

**Comment by david1597** [comment]
Primary data from ScienceCloud is now on my [ELN](https://au-mynotebook.labarchives.com/share/David%2520Smith%2520OSM/MjQ4LjN8MzAxNzEvMTkxL1RyZWVOb2RlLzc1OTA1MzMzMXw2MzAuMw==). This ELN link has also been added to the Not Yet On The Wiki page.

Also, pdf of the two runs are below as direct links:
[Dundee_Feb18_ScienceCloud_MMV11_0040_18ANDM-017_25uM.pdf](https://github.com/OpenSourceMalaria/Series4/files/1887135/Dundee_Feb18_ScienceCloud_MMV11_0040_18ANDM-017_25uM.pdf)
[Dundee_Feb18_ScienceCloud_MMV11_0040_18ANDM-018_25uM.pdf](https://github.com/OpenSourceMalaria/Series4/files/1887136/Dundee_Feb18_ScienceCloud_MMV11_0040_18ANDM-018_25uM.pdf).

**Comment by mattodd** [comment]
Neil Norcross wrote by email today, after seeing the latest data. He recommended a focus on OSM-S-525:

"I would resynthesize and retest this compound in the first instance, to ensure this is a true result.

If it is, you might want to consider the 4 compounds below, to follow up on MMV1579341.

![variants of 525](https://user-images.githubusercontent.com/4386101/38478801-57ec1ea6-3bfe-11e8-9705-deb95d548771.png)

Reducing the number of aromatic rings and logP would be a priority. 

Do you have any mammalian (counter screen) cell data? Mouse hepatocyte, solubility and PAMPA data would also be very useful, if possible. _(MHT - tox was included in the original screen? We're getting rat hep, sol soon)_

**Key questions**:

How important is the NH of the indole?

Is moving the NH2 from the para (MMV1579342) to the meta position better tolerated, in line with the indole NH?

Does the 5 membered ring (mr) of the indole need to be aromatic or can the double bond be reduced (to the aliphatic 5 mr)?

Can the logP be reduced further by introducing polar groups into the 5 membered ring (amide or sulphonamide) and are they tolerated?

Also, how metabolically stable is the phenol ether (O-dealkylation)?" (MHT - this was assessed some time ago OpenSourceMalaria/OSM_To_Do_List#334)

Strings:
1
FC1=C(F)C=CC(CCOC2=CN=CC3=NN=C(C4=CC(N)=CC=C4)N32)=C1
InChI=1S/C19H15F2N5O/c20-15-5-4-12(8-16(15)21)6-7-27-18-11-23-10-17-24-25-19(26(17)18)13-2-1-3-14(22)9-13/h1-5,8-11H,6-7,22H2
CQZOPOXKTPBXOH-UHFFFAOYSA-N

2
FC1=C(F)C=CC(CCOC2=CN=CC3=NN=C(C4=CC(NCC5)=C5C=C4)N32)=C1
InChI=1S/C21H17F2N5O/c22-16-4-1-13(9-17(16)23)6-8-29-20-12-24-11-19-26-27-21(28(19)20)15-3-2-14-5-7-25-18(14)10-15/h1-4,9-12,25H,5-8H2
FNBXJZBLBXZUFU-UHFFFAOYSA-N

3
FC1=C(F)C=CC(CCOC2=CN=CC3=NN=C(C4=CC(NC(C5)=O)=C5C=C4)N32)=C1
InChI=1S/C21H15F2N5O2/c22-15-4-1-12(7-16(15)23)5-6-30-20-11-24-10-18-26-27-21(28(18)20)14-3-2-13-9-19(29)25-17(13)8-14/h1-4,7-8,10-11H,5-6,9H2,(H,25,29)
PUDALCIATSASSD-UHFFFAOYSA-N

4
FC1=C(F)C=CC(CCOC2=CN=CC3=NN=C(C4=CC(NS(C5)(=O)=O)=C5C=C4)N32)=C1
InChI=1S/C20H15F2N5O3S/c21-15-4-1-12(7-16(15)22)5-6-30-19-10-23-9-18-24-25-20(27(18)19)13-2-3-14-11-31(28,29)26-17(14)8-13/h1-4,7-10,26H,5-6,11H2
JPYPGECXOMLEIE-UHFFFAOYSA-N

**Comment by MFernflower** [comment]
That sulfur compound has a very attractive predicted LogP - @mattodd is the boronic acid needed commercially available?

**Comment by cdsouthan** [comment]
Convergent thinking on resyn/retest (but I was a week ahead :)

![capture](https://user-images.githubusercontent.com/3713939/38483106-13bfbf02-3bd2-11e8-86d2-d913fda04626.JPG)

**Comment by cdsouthan** [comment]
While  we are pushing for final data for the paper it would be good to have a technical discussion with Dundee and MMV about a re-assay campaign for the front runners/ sub 100 nM hits.   Its great to see the  raw data from Dundee (and full credit for their turnaround)  but its clear from the charts that these are scoping IC50s with big error ranges (even missing points on the inflections  in some cases).  As @david1597 indicated elsewhere,  if the repeats are coming in with ranges of ~2-fold  we are ending up with jellyfish SAR.  For comparison, data from  @MedChemProf  PfATP4_mutantsummary_MCPHS.pdf  are more towards the tighter side we need (e.g. ~ 30% ).

**Comment by MFernflower** [comment]
What do you mean by jellyfish SAR - we have a bunch of diffrent stuff that works but dont know why? @cdsouthan

**Comment by mattodd** [comment]
Further thoughts just in from Neil Norcross by email:

A few more points to consider, if the ‘meta aniline’ is tolerated, you could replace the Cl for a F at the para position, which could work in a number of different ways: reduce logP, form an intra molecular H-bond to improve permeability, pull electron density away from the NH2, reducing nucleophilicity but also increasing H-bond potential of an NH (one H bond would be tied up with the F atom), this could reduce the reactivity of the aniline to possible glucoronidation also, so mouse hepatocyte data will be key here.  In addition, you would need to get any aniline of interest tested for AMES, sooner rather than later.  Also, changing the electronics of the ring can have a huge impact on whether a compound is AMES positive or negative.  

If the aniline at the meta position is key for activity and/or selectivity, you could always put a nitrogen atom at the para position (instead of the chlorine), giving you the amino pyridine, which could be very useful, if tolerated.  The amino pyridine will modulate the pKa of the aniline (can increase pKa by 2 log units), so if aniline has a pKaH of ca. 5, the amino pyridine could have a pKaH of ca. 7.  (The pKa of the amino pyridine can also be impacted by the electronics of the adjacent ring).  If the aminopyridine is protonated at physiological pH, this may also improve your solubility and potentially, modulate in vivo properties such as volume of distribution and half-life. Also, compared to the aniline, the amino pyridine moiety can mitigate AMES and/or glucoronidation.

![variants of 525 part 2](https://user-images.githubusercontent.com/4386101/38596829-1e7cec0a-3d97-11e8-894b-fb2f65c5ac2c.png)

I would be cautious about adding the acid groups (meta or para), which is likely to kill your permeability (in vitro and in vivo) and may also impact on getting into red blood cells, for antimalarial screening.  I appreciate that you can use acid bioiosteres as a replacement but it’s certainly something to be wary of.

[Variants of 525 Part 2.zip](https://github.com/OpenSourceMalaria/Series4/files/1897295/Variants.of.525.Part.2.zip)

Strings
5
FC1=C(F)C=CC(CCOC2=CN=CC3=NN=C(C4=CC(N)=C(F)C=C4)N32)=C1
InChI=1S/C19H14F3N5O/c20-13-3-1-11(7-15(13)22)5-6-28-18-10-24-9-17-25-26-19(27(17)18)12-2-4-14(21)16(23)8-12/h1-4,7-10H,5-6,23H2
VZPHEOZUAXBEIA-UHFFFAOYSA-N

6
FC1=C(F)C=CC(CCOC2=CN=CC3=NN=C(C4=CC(N)=NC=C4)N32)=C1
InChI=1S/C18H14F2N6O/c19-13-2-1-11(7-14(13)20)4-6-27-17-10-22-9-16-24-25-18(26(16)17)12-3-5-23-15(21)8-12/h1-3,5,7-10H,4,6H2,(H2,21,23)
FKGHXQVSFJVZKU-UHFFFAOYSA-N

**Comment by MFernflower** [comment]
Reading Neil's musings gave me this rather crazy but possibly effective idea: 
![djdijeje](https://user-images.githubusercontent.com/3164942/38597377-4f88e5e6-3d25-11e8-8f7b-3b635ab8800f.png) @mattodd
