### ISSUE TITLE
5-S-linked pyrazine side chains

### ISSUE THREAD

**Issue by edwintse** [OpenSourceMalaria/Series4#49]
Parallel to the 5-N-linked experiments that @david1597 is [currently doing](https://github.com/OpenSourceMalaria/Series4/issues/47), I am repeating the experiments that gave me the original thioether compounds (EGT 48-1 and EGT 52-1) as part of the [larger investigation](https://github.com/OpenSourceMalaria/Series4/issues/46).

Below are the HNMRs of the original compounds that I made which came back inactive. EGT 48-1 shows the expected singlets for the pyrazine protons, while EGT 52-1 is lacking the expected singlet at ~9 ppm and is actually showing doublets (which suggests this is actually the 8-substituted product)
![old](https://user-images.githubusercontent.com/18062981/40642902-c35f9462-6361-11e8-966c-dd2437871680.jpg)

----------------------------------------------------------------------------------------------------

I have repeated both coupling reactions and have found that I'm getting a **mix of both the 5- and 8-substituted products**. The 4 lanes in the TLC below are as follows: 1) triazolopyrazine core, 2) co-spot, 3) [EGT 48-2](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/OTQ5LjB8MTUwOS83MzAvVHJlZU5vZGUvMjY4NTY1ODkyOHwyNDA5LjA=), 4) [EGT 52-2](https://au-mynotebook.labarchives.com/share/Edwin%2520Tse/OTUwLjMwMDAwMDAwMDAwMDF8MTUwOS83MzEvVHJlZU5vZGUvNDQwMDMxMjI0fDI0MTIuMjk5OTk5OTk5OTk5Nw==) (ELN links in 3 and 4). It is clear that in both cases there are two spots (one less polar than the core; typical of the 8-sub'd product, and one more polar than the core; typical of the 5-sub'd product)
![untitled wiley-3](https://user-images.githubusercontent.com/18062981/40643252-da893354-6362-11e8-8884-c726f33128ff.jpeg)
Both reactions have been columned and I have isolated both the 5- and 8-sub'd products in each case (HNMRs shown below). In both cases, there is a 92-93% combined yield indicating no other side-products were formed. Interestingly, the ratios of 5- to 8-sub'd products are switched between the 1C and 2C chain lengths. For the 1C chain, there is a majority of the 5-sub'd product (1:0.18 of the 5-/8-sub'd products). For the 2C chain, there is a majority of the 8-sub product (1:1.5 of the 5-/8-sub'd product)
![thioether repeat](https://user-images.githubusercontent.com/18062981/40643525-c43736f4-6363-11e8-88eb-679827dccfdb.jpg)

----------------------------------------------------------------------------------------------------

This is the first instance in which we've been able to clearly see and isolate both products from a single reaction. @maratsydney's N-heterocyclic compounds have given exclusively the 8-sub'd product, the standard OH coupling gives exclusively the 5-sub'd product, and @david1597's alkyl amine couplings are exclusively giving the 8-sub'd product.

**n.b.** The original oxidised thioether compounds (EGT45, EGT39, EGT60 and EGT63) which came back inactive as well are all the actual 5-sub'd products as they were made through a different route (sulfur was attached directly to the 2,6-dichloropyrazine SM then oxidised, hydrazine displacement, condensation, then cyclisation).

All 4 products will be sent for evaluation in the next batch.

**Comment by mcoster** [comment]
Great work Ed! I guess the details are in your ELN, but I'd be curious to know how you run these reactions. Is it thiol plus K2CO3 or similar? Also, has thiophenol been used for this chemistry?

**Comment by edwintse** [comment]
The reaction conditions I used are: Thiol (1 eq.), core (1 eq.), KOH (3.3 eq.), 18-crown-6 (0.08 eq.), PhMe (10 mL/100 mg of core), rt, 3 h.
(I've also updated the post with ELN links).

The corresponding thiophenol compound hasn't been made before . I may try this to see if I get exclusively the 5-sub'd product (perhaps the ratio of different products in the thiol case have something to do with the chain length?)

**Comment by drc007** [comment]
Very nice, perhaps also oxidise to sulphoxide and sulphone?

**Comment by drc007** [comment]
Very nice, perhaps also oxidise to sulphoxide and sulphone?

**Comment by edwintse** [comment]
Yes, I've made both the 1C and 2C chain sulfoxides and sulfones when I was originally doing the thioether series. They were all inactive.

**Comment by MedChemProf** [comment]
(@edwintse / @maratsydney) I just wanted to interject a few thoughts to the discussion and ongoing work. Firstly, I’ll echo this was some good detective work by all to isolate and characterize the 8-substitutued versus the 5-substitutued product. I will caution however, rushing in and running too many repeat experiments before looking at the examples that are already definitive in their results. It is already been proven that the alcohol nucleophiles and azide give either predominately or exclusively the 5-substituted product, whereas the thiol tends to give the 8-substitutued product (along with some possible steric influence on selectivity.) I chose to mention these three nucleophiles because they span the range of Hard Lewis Base (the alcohol), to mid-range Lewis Base (the Azide) and Soft Lewis Base (the Thiol). It is my opinion that we are simply seeing a distribution of products from a Hard/Soft-Acid/Base argument. Both products are formed via a nucleophilic aromatic substitution reaction followed by an eventual elimination reaction, but the initial substitution location is based on the appropriate HOMO/LUMO alignments. The reason that I suggested not running too many more experiments is that the dramatic difference between the Azide selectivity and the Thiol indicate that there may be a very nuanced preference electronically. It may be best to spend some time in silico first and recruit someone who might be able to provide you with some basic calculations along the Hard/Soft-Acid/Base line of thinking to see if it matches what you already have in hand before expending effort on the bench.

Secondly, there seems to be a number of analogs already made that are substituted at the 8-position and they are all inactive. I do not recommend any further effort be expended making even more analogs at that position unless they are dedicated to studying the mechanistic line of inquiry.

Finally, a lot of great science and science education has been taking place over the past 8-10 months (and maybe that is a justification for Open Science in itself), but I personally have seemed to have lost sight of the target compound profile that we collectively are aiming for at the moment. I am still planning on synthesizing the targets that I mentioned in @david1597 #44 thread, but for economy and efficiency sake, are we still making the right compounds?

**Comment by MFernflower** [comment]
@MedChemProf While I cannot comment for the rest of the team - I think it would be best to try and focus on your structure hops - perhaps using difluorophenylethanol as the LHS alcohol instead of the triol to save time?

**Comment by edwintse** [comment]
@MedChemProf I agree that if it is indeed comes down to the hard/soft-acid/base nature of the nucleophile then some modelling/calculations would be a good way to go from here.

While you are correct in that the analogs that we have found to be 8-sub'd are all inactive, we are not intending to make any more of these products. As we've found a number of these 8-sub'd products, a gap has been left in our SAR (in particular for the amine linkers and the thiol linkers) that we now needs to be filled. The experiments I've just done have filled this gap for the thiol linkers, and we will need to wait for potency to see if any further experiments are required. As for the amine linker, @david1597 has not yet been able to make the actual 5-sub'd product and is only getting the 8-sub'd product so we still need to run experiments until we can isolate some 5-sub'd product.

Perhaps @mattodd can comment more about the TCP, but I think the compounds you are targeting are still important for the project.

**Comment by david1597** [comment]
@MedChemProf Ed beat me to the comment but pretty much what he said. We're not so much aiming to make more 8-substituted products, we're aiming to make new 5 substituted ones. Particularly the amines, we don't have any from this series in our library. Worse is that we thought we did, and had completely dismissed them for a long time by believing them to be inactive. I think our repeats so far have been crucial - Ed has just found that we do indeed get both products forming when using thiols - we didn't realise this at all until yesterday. That is it for the thiol cases, I currently have 4 more reactions stirring with the amines and again, that may be it for a while once they're complete.

Regarding general direction and are we still making the right compounds. I think this deserves a fresh issue sometime soon (maybe once the April potency results are back, _any_ day now...). We have quite a lot going on in terms of synthesis (which is great - and great that this is happening over a wide area, both chemically and geographically!) For your compounds, I think those you suggested in #44 are spot on. I'll expand my comments regarding those compounds on that thread shortly.

**Comment by MFernflower** [comment]
@david1597 When you get a chance can you move Dr.Smith's structure hops to another issue? I will be commenting about them once the issue is posted

**Comment by mattodd** [comment]
Hi @MedChemProf - thanks for your comment. Ed and David nailed the answer, I think. The current experiments are around understanding the organic chem (because the SNAR route has been widely used and we'd missed this beautiful rearrangement) and the SAR (which we now realise has holes - holes that were also present in the original, inherited SAR which may have suffered the same complication). Nobody wants more analogs with 8-subst, except for orgchem reasons.

The aims remain unchanged - sub 10nM potency with good solubility and slow clearance. The Pfizer compound and the Suzuki indole have raised new prospects of such compounds - they are surprisingly potent and have good predicted logP. We need to direct remaining synthetic efforts towards these while we're writing up the Series 4 paper since they *may* (we all hope, I'm sure) provide the capstone (some might say "punchline") for the S4 paper. Your idea of NH2 in place of OH for the Pfizer compound is perfect, as I just commented over at #50 . 

We do need an OSM meeting in June, to talk through strategy. I'll be considerably less online in July and August during my transit to London, after which I'm back on board 100%. During those two months the OSM team is more than able to direct operations, but we should have a clear list of primary objectives and timelines.

**Comment by edwintse** [comment]
Experiments around this have concluded and potency has been received (#54). Closing
